knpu_oauth2_client:
  clients:
    # https://developers.google.com/identity/protocols/oauth2?hl=fr
    # https://console.cloud.google.com/apis/credentials?authuser=2&hl=fr&project=pokenini-app
    google:
      type: google
      client_id: ~
      client_secret: ~
      redirect_route: app_connect_google_check
      redirect_params: {}

    # https://discord.com/developers/docs/topics/oauth2
    # https://discord.com/developers/applications
    discord:
      type: discord
      client_id: ~
      client_secret: ~
      redirect_route: app_connect_discord_check
      redirect_params: {}

when@test:
  knpu_oauth2_client:
    clients:
      mock:
        type: generic
        provider_class: App\Security\MockProvider
        client_id: ~
        client_secret: ~
        redirect_route: app_connect_mock_check
        redirect_params: {}
