security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    users:
        id: App\Security\UserProvider

  firewalls:
    back:
      pattern: ^/
      access_token:
          token_handler: App\Security\AccessTokenHandler
          token_extractors: header

  access_control:
    - { path: ^/istration, roles: ROLE_ADMIN }
    - { path: ^/, roles: ROLE_USER }