security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  
  providers:
    users:
      # id: App\Security\UserProvider
      memory:
        users:
          web: { password: '%env(WEB_PASSWORD)%', roles: ["ROLE_BACK"] }

  firewalls:
    back:
      pattern: ^/
      stateless: true
      lazy: false
      provider: users
      http_basic:
        realm: Secured Area
      # lazy: true
      # provider: users
      # logout:
      #   path: app_connect_logout
      # entry_point: App\Security\AuthenticationEntryPoint
      # custom_authenticators:
      #   - App\Security\AmazonAuthenticator
      #   - App\Security\DiscordAuthenticator
      #   - App\Security\GoogleAuthenticator
      #   - App\Security\PassageAuthenticator

  access_control:
    - { path: ^/, roles: ROLE_BACK }

when@test:
  security:            
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
