security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    users:
      id: App\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: users
      access_token:
        token_handler: App\Security\AccessTokenHandler
        token_extractors: header

  access_control:
    - { path: ^/istration, roles: ROLE_ADMIN }
    - { path: ^/user-info, roles: PUBLIC_ACCESS }
    - { path: ^/album, roles: PUBLIC_ACCESS }
    - { path: ^/labels, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
