name: CI Infra Quality

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Docker Hub token'
        required: true

env: 
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  docker-compose-lint:
    name: Docker Compose Linter
    runs-on: ubuntu-latest
    container:
      image: zavoloklom/dclint:2.2.2-alpine
      volumes:
        - ${{ github.workspace }}:/app
    steps:
    - uses: actions/checkout@v5
    - run: /bin/dclint -r .

  dotenv-lint:
    name: DotEnv Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Lint .env* files
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          tool_name: DotEnv Linter
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
          dotenv_linter_flags: --recursive

  dockerfile-lint:
    name: Dockerfile Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Lint moco Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./.docker/moco/Dockerfile
      - name: Lint php Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./.docker/php/Dockerfile
